/**
 * Chaos
 * Central Management API - publicly exposed set of APIs for cloud resources
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: help@qernal.support
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from "./configuration";
import type { RequestArgs } from "./base";
import type { AxiosInstance, AxiosResponse } from 'axios';
export declare const DUMMY_BASE_URL = "https://example.com";
/**
 *
 * @throws {RequiredError}
 */
export declare const assertParamExists: (functionName: string, paramName: string, paramValue: unknown) => void;
export declare const setApiKeyToObject: (object: any, keyParamName: string, configuration?: Configuration) => Promise<void>;
export declare const setBasicAuthToObject: (object: any, configuration?: Configuration) => void;
export declare const setBearerAuthToObject: (object: any, configuration?: Configuration) => Promise<void>;
export declare const setOAuthToObject: (object: any, name: string, scopes: string[], configuration?: Configuration) => Promise<void>;
export declare const setSearchParams: (url: URL, ...objects: any[]) => void;
export declare const serializeDataIfNeeded: (value: any, requestOptions: any, configuration?: Configuration) => any;
export declare const toPathString: (url: URL) => string;
export declare const createRequestFunction: (axiosArgs: RequestArgs, globalAxios: AxiosInstance, BASE_PATH: string, configuration?: Configuration) => <T = unknown, R = AxiosResponse<T>>(axios?: AxiosInstance, basePath?: string) => Promise<R>;
